name: punker76
description: "Husband, dad, software programmer, developer, coder, MahApps.Metro collaborator... Punk's not dead!"
meta_description: "Hi, this is my private blog about some thoughts and other stuff."

markdown: redcarpet
redcarpet:
  extensions: ["tables"]
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jkarger.de'
permalink: /archive/:year/:month/:day/:title/

# Details for the RSS feed generator
url:            'http://jkarger.de'
author:         'punker76'

# Disqus Comments
disqus_short_name: jkarger
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-56992653-1

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
