# Site settings
title: punker76
description: 'another private blog with developer stuff and some thoughts'
url: 'http://jkarger.de'
baseurl: '/'
google_analytics: 'UA-56992653-1'
disqus_shortname: 'jkarger'

author:
  name: 'Jan Karger'
  email: punkerat76@gmail.com
  twitter_username: punker76
  facebook_username: punker76
  github_username:  punker76
  linkedin_username:  punker76

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
#permalink: /:year/:title/
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-mentions', 'jekyll-sitemap', 'jemoji']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
