# Site settings
author      : Jan Karger
nickname    : punker76
title       : jkarger.de
subtitle    : Punk's not dead!
description: > # this means to ignore newlines until "baseurl:"
  Hi, this is my private blog about some thoughts and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jkarger.de" # the base hostname & protocol for your site

twitter_username : punker76
github_username  : punker76

# Build settings
markdown      : redcarpet # or kramdown
redcarpet :
  extensions  : ["tables"]
paginate      : 5
permalink     : /archive/:year/:month/:day/:title/

# comments -> disqus
comments :
  provider : disqus
  disqus :
    short_name : punker76
